// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sqlc

import (
	"database/sql"
	"time"
)

type Event struct {
	EventID        int32          `json:"event_id"`
	EventName      string         `json:"event_name"`
	EventBody      sql.NullString `json:"event_body"`
	EventStartDate sql.NullTime   `json:"event_start_date"`
	EventEndDate   sql.NullTime   `json:"event_end_date"`
}

type Reply struct {
	ReplyID          int32     `json:"reply_id"`
	ReplyBody        string    `json:"reply_body"`
	ThreadID         int32     `json:"thread_id"`
	ReplyCreatedBy   int32     `json:"reply_created_by"`
	ReplyCreatedAt   time.Time `json:"reply_created_at"`
	ReplyLastUpdated time.Time `json:"reply_last_updated"`
}

type SchemaMigration struct {
	Version int64 `json:"version"`
	Dirty   bool  `json:"dirty"`
}

type Thread struct {
	ThreadID        int32     `json:"thread_id"`
	ThreadName      string    `json:"thread_name"`
	ThreadBody      string    `json:"thread_body"`
	ThreadCreatedBy int32     `json:"thread_created_by"`
	ThreadCreatedAt time.Time `json:"thread_created_at"`
}

type User struct {
	UserID      int32     `json:"user_id"`
	Username    string    `json:"username"`
	Password    string    `json:"password"`
	Email       string    `json:"email"`
	TimeCreated time.Time `json:"time_created"`
}
