// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sqlc

import (
	"database/sql"
	"time"
)

// forum categories
type Category struct {
	CatID     int32        `json:"cat_id"`
	CatName   string       `json:"cat_name"`
	CreatedBy int32        `json:"created_by"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Event struct {
	EventID        int32          `json:"event_id"`
	EventName      string         `json:"event_name"`
	EventBody      sql.NullString `json:"event_body"`
	EventStartDate sql.NullTime   `json:"event_start_date"`
	EventEndDate   sql.NullTime   `json:"event_end_date"`
}

type Hyperlink struct {
	LinkID   int32          `json:"link_id"`
	LinkName string         `json:"link_name"`
	LinkBody sql.NullString `json:"link_body"`
}

// forum posts
type Post struct {
	PostID      int32     `json:"post_id"`
	Title       string    `json:"title"`
	Body        string    `json:"body"`
	CategoryID  int32     `json:"category_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedBy   int32     `json:"created_by"`
	LastUpdated time.Time `json:"last_updated"`
}

type User struct {
	UserID      int32     `json:"user_id"`
	Username    string    `json:"username"`
	Password    string    `json:"password"`
	Email       string    `json:"email"`
	TimeCreated time.Time `json:"time_created"`
}

type UserKeepTrack struct {
	ID      int32         `json:"id"`
	UserID  sql.NullInt64 `json:"user_id"`
	EventID sql.NullInt64 `json:"event_id"`
}
