name: Go package

on:
  # on: [push] works too
  push:
    branches: [main, forum]

jobs:
  # this is the name
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Install dependencies
        run: |
          cd backend
          go get -v -t ./...

      - name: Build
        run: |
          cd backend
          go build -v ./...

      - name: Test
        run: |
          cd backend
          go test -v ./...

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/orbitalbackend:latest

  #### this wont work because of VPC issue
  # Deploy:
  #   needs: build_and_push
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Deploy in EC2
  #       env:
  #         PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
  #         HOSTNAME: ${{ secrets.EC2_USER_HOSTNAME  }}

  #       run: |
  #         echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
  #         ssh -o StrictHostKeyChecking=no -i private_key $HOSTNAME '

  #          docker login
  #          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/orbitalbackend:latest
  #          docker run -d -p 80:8080 orbitalbackend:latest

  #         '
