name: CD Pipeline
# taken from https://www.youtube.com/watch?v=rRes9LM-Jh8&t=569

on:
  workflow_run:
    workflows: ["Backend_Build_Pipeline"]
    types:
      - completed
jobs:
  build:
    runs-on: self-hosted
    # env:
    #   DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    #   DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker Image
        run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/orbitalbackend:latest
      - name: Remove old containers
        run: sudo docker rm -f $(sudo docker ps -a -q) || true
      - name: Run Docker Container
        run: sudo docker run -d -p 80:8080 ${{ secrets.DOCKERHUB_USERNAME }}/orbitalbackend:latest
